#!/usr/bin/env python3
"""
Auto-generated unit tests for prime_checker.py
Generated by Claude Code hooks system.
"""

import unittest
import sys
import os

# Add the parent directory to sys.path to import the module
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

try:
    from prime_checker import *
except ImportError as e:
    print(f"Could not import prime_checker: {e}")
    sys.exit(1)


class TestPrime_CheckerFunctions(unittest.TestCase):
    """Test cases for module functions."""

    def test_is_prime(self):
        """Test is_prime function."""
        # Test with known prime numbers
        self.assertTrue(is_prime(2))
        self.assertTrue(is_prime(17))
        self.assertFalse(is_prime(4))
        self.assertFalse(is_prime(1))
        pass  # Remove this when adding real tests

    def test_main(self):
        """Test main function."""
        # Add test cases for main
        # Example: result = main()
        # self.assertIsNotNone(result)
        pass  # Remove this when adding real tests


if __name__ == '__main__':
    unittest.main(verbosity=2)
